#!/usr/bin/env bash

# Get the directory where the script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the backend directory (parent of bin)
BACKEND_DIR="$(cd "${SCRIPT_DIR}/../backend" && pwd)"
# Export environment variables from .env file
set -a
source "${BACKEND_DIR}/.env"
set +a

# Define Docker Compose command
DOCKER_COMPOSE="docker-compose -f ${BACKEND_DIR}/build/docker-compose.yml"
# PHP container name
PHP_CONTAINER=${DOCKER_CONTAINER_PHP:-"php"}
# Docker exec command
EXEC="docker exec -it ${PHP_CONTAINER}"
# Console command
CONSOLE="${EXEC} php bin/console"

CMD=${1:-""}

$CONSOLE $CMD
